/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_persist_util_tool_analysis_CalculatorImpl */

#ifndef _Included_com_persist_util_tool_analysis_CalculatorImpl
#define _Included_com_persist_util_tool_analysis_CalculatorImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_persist_util_tool_analysis_CalculatorImpl
 * Method:    predict
 * Signature: (Ljava/util/List;ILjava/lang/String;Ljava/lang/String;II)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_com_persist_util_tool_analysis_CalculatorImpl_predict
  (JNIEnv *, jobject, jobject, jint, jstring, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
