/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_persist_util_tool_analysis_Predict */

#ifndef _Included_com_persist_util_tool_analysis_Predict
#define _Included_com_persist_util_tool_analysis_Predict
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_persist_util_tool_analysis_Predict
 * Method:    predict
 * Signature: (Ljava/util/List;)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_com_persist_util_tool_analysis_Predict_predict
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
